"""
UrbanShield - Priority Ranking Table Component
Renders the ranked urgency table generated by the PRIORITIZE & OPTIMIZE layers.
Connects the full decision pipeline: SENSE -> PREDICT -> PRIORITIZE -> OPTIMIZE -> RECOMMEND.
"""

import streamlit as st
import pandas as pd
from config import SEVERITY_CONFIG
from services.data_service import get_zones_summary
from services.agent_service import get_pipeline_predictions, get_recommendations_and_allocations

def render_priority_table() -> str:
    """
    Renders ranked urgency table and explainable decision drilldown.
    Synchronizes st.session_state['selected_zone_id'] across map and recommendation views.
    """
    current_selected = st.session_state.get("selected_zone_id", "Z-01")

    try:
        with st.spinner("Compiling priority ranking matrix..."):
            zones_list = get_zones_summary() or []
            zones_by_id = {z["zone_id"]: z for z in zones_list}
            
            predictions = get_pipeline_predictions() or []
            recommendations = get_recommendations_and_allocations() or {}

        # ---------------------------------------------------------------------
        # 1. EMPTY STATE GUARD
        # ---------------------------------------------------------------------
        if not predictions or not zones_list:
            st.info("ℹ️ **No priority data available.** Connect backend infrastructure feeds or refresh telemetry.")
            return current_selected

        # ---------------------------------------------------------------------
        # 2. MERGE DATA INTO STRUCTURED RANKED ROWS
        # ---------------------------------------------------------------------
        table_rows = []
        sorted_preds = sorted(predictions, key=lambda x: x.get("priority_rank", 99))

        for pred in sorted_preds:
            z_id = pred.get("zone_id", "Z-XX")
            z_info = zones_by_id.get(z_id, {})
            recs = recommendations.get(z_id, {})
            
            severity = pred.get("severity", "Low")
            badge = SEVERITY_CONFIG.get(severity, {}).get("badge", severity)
            risk_val = pred.get("risk_score", 0.0)
            
            pumps = recs.get("allocated_pumps", 0)
            crews = recs.get("allocated_crews", 0)
            res_str = f"🚜 {pumps} Pumps, 👷 {crews} Crews" if (pumps > 0 or crews > 0) else "⚡ Standby (0 Deployed)"

            table_rows.append({
                "Rank": f"#{pred.get('priority_rank', '-')}",
                "Asset / Zone": f"[{z_id}] {z_info.get('name', z_id)}",
                "Asset Type": z_info.get("asset_type", "Municipal Infrastructure"),
                "Risk Score": f"{int(risk_val * 100)}% ({risk_val:.2f})",
                "Severity": badge,
                "Allocated Resources": res_str,
                "Recommended Action": recs.get("action_summary", "Monitor baseline sensors")
            })

        df = pd.DataFrame(table_rows)

        st.markdown("##### 🏆 Ranked Priority & Resource Allocation (OR-Tools + Random Forest)")
        st.dataframe(
            df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Rank": st.column_config.TextColumn("Rank", width="small"),
                "Asset / Zone": st.column_config.TextColumn("Asset / Zone", width="medium"),
                "Asset Type": st.column_config.TextColumn("Type", width="small"),
                "Risk Score": st.column_config.TextColumn("Risk Score", width="small"),
                "Severity": st.column_config.TextColumn("Severity", width="small"),
                "Allocated Resources": st.column_config.TextColumn("Allocated Resources", width="medium"),
                "Recommended Action": st.column_config.TextColumn("Recommended Action", width="large")
            }
        )

        # ---------------------------------------------------------------------
        # 3. INTERACTIVE ZONE FOCUS & END-TO-END PIPELINE TRACE
        # ---------------------------------------------------------------------
        with st.expander("🔍 Zone Inspection & End-to-End Decision Pipeline Trace", expanded=True):
            st.caption("Inspect how raw telemetry flows step-by-step through SENSE -> PREDICT -> PRIORITIZE -> OPTIMIZE -> RECOMMEND -> SIMULATE.")
            
            zone_options = [f"{z['zone_id']} - {z['name']} ({z.get('asset_type', 'Infrastructure')})" for z in zones_list]
            if not zone_options:
                return current_selected
                
            # Guarantee bidirectional synchronization with st.session_state["selected_zone_id"]
            matched_option = next((opt for opt in zone_options if opt.startswith(current_selected)), zone_options[0])
            if st.session_state.get("priority_zone_selector") != matched_option:
                st.session_state["priority_zone_selector"] = matched_option

            def _on_priority_selector_change():
                val = st.session_state.get("priority_zone_selector")
                if val:
                    st.session_state["selected_zone_id"] = val.split(" - ")[0]

            selected_zone_str = st.selectbox(
                "🎯 Focus Zone on Map & Action Brief:",
                zone_options,
                key="priority_zone_selector",
                on_change=_on_priority_selector_change
            )
            selected_zone_id = selected_zone_str.split(" - ")[0]
            st.session_state["selected_zone_id"] = selected_zone_id

            selected_zone = zones_by_id.get(selected_zone_id, {})
            selected_pred = next((p for p in predictions if p.get("zone_id") == selected_zone_id), {})
            selected_rec = recommendations.get(selected_zone_id, {})
            
            # -----------------------------------------------------------------
            # 4. EXPLICIT 6-STAGE DECISION TRACE TILES
            # -----------------------------------------------------------------
            st.markdown("###### ⚡ Complete Pipeline Trace for Selected Asset:")
            
            c_sense, c_pred, c_prio, c_opt, c_rec, c_sim = st.columns(6)
            
            with c_sense:
                st.markdown(
                    f"""
                    <div style="background-color: #1E293B; border-top: 3px solid #3B82F6; border-radius: 6px; padding: 8px 6px; font-size: 0.76rem;">
                        <div style="color: #60A5FA; font-weight: bold;">1. SENSE</div>
                        <div>🌧️ <b>Rain:</b> {selected_zone.get('rainfall_mm_per_hr', 0)} mm/h</div>
                        <div>🚰 <b>Drain:</b> {selected_zone.get('drainage_capacity_pct', 0)}%</div>
                        <div>💧 <b>Soil:</b> {selected_zone.get('soil_saturation_pct', 0)}%</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            with c_pred:
                r_score = selected_pred.get('risk_score', 0.0)
                sev = selected_pred.get('severity', 'Low')
                sev_color = SEVERITY_CONFIG.get(sev, {}).get("color", "#10B981")
                st.markdown(
                    f"""
                    <div style="background-color: #1E293B; border-top: 3px solid #8B5CF6; border-radius: 6px; padding: 8px 6px; font-size: 0.76rem;">
                        <div style="color: #A78BFA; font-weight: bold;">2. PREDICT</div>
                        <div>🎯 <b>Risk:</b> <span style="color: {sev_color}; font-weight:bold;">{r_score:.2f}</span></div>
                        <div>⚠️ <b>Lvl:</b> {sev}</div>
                        <div>🤖 <b>ML:</b> RF Model</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            with c_prio:
                p_rank = selected_pred.get('priority_rank', '-')
                pop = selected_zone.get('population', 0)
                st.markdown(
                    f"""
                    <div style="background-color: #1E293B; border-top: 3px solid #EC4899; border-radius: 6px; padding: 8px 6px; font-size: 0.76rem;">
                        <div style="color: #F472B6; font-weight: bold;">3. PRIORITIZE</div>
                        <div>🏆 <b>Rank:</b> #{p_rank} of {len(predictions)}</div>
                        <div>👥 <b>Pop:</b> {pop:,}</div>
                        <div>🛡️ <b>Weight:</b> Conseq.</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            with c_opt:
                p_alloc = selected_rec.get('allocated_pumps', 0)
                c_alloc = selected_rec.get('allocated_crews', 0)
                st.markdown(
                    f"""
                    <div style="background-color: #1E293B; border-top: 3px solid #F59E0B; border-radius: 6px; padding: 8px 6px; font-size: 0.76rem;">
                        <div style="color: #FBBF24; font-weight: bold;">4. OPTIMIZE</div>
                        <div>🚜 <b>Pumps:</b> {p_alloc} Deployed</div>
                        <div>👷 <b>Crews:</b> {c_alloc} Deployed</div>
                        <div>🧩 <b>Solver:</b> OR-Tools</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            with c_rec:
                urg = selected_rec.get('urgency', 'Standard')
                short_urg = urg.split('(')[0].strip()
                st.markdown(
                    f"""
                    <div style="background-color: #1E293B; border-top: 3px solid #10B981; border-radius: 6px; padding: 8px 6px; font-size: 0.76rem;">
                        <div style="color: #34D399; font-weight: bold;">5. RECOMMEND</div>
                        <div>🚀 <b>Mode:</b> {short_urg}</div>
                        <div>📋 <b>Order:</b> Dispatched</div>
                        <div>✅ <b>Status:</b> Ready</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            with c_sim:
                st.markdown(
                    """
                    <div style="background-color: #1E293B; border-top: 3px solid #06B6D4; border-radius: 6px; padding: 8px 6px; font-size: 0.76rem;">
                        <div style="color: #22D3EE; font-weight: bold;">6. SIMULATE</div>
                        <div>🔄 <b>What-If:</b> Active</div>
                        <div>📊 <b>Presets:</b> 4 Ready</div>
                        <div>⚡ <b>Recalc:</b> Live</div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            st.markdown("<div style='margin-bottom: 6px;'></div>", unsafe_allow_html=True)
            st.markdown(f"**🛡️ Protected Critical Infrastructure:** {', '.join(selected_zone.get('critical_assets', ['Standard Urban Infrastructure']))}")
            st.markdown(f"**💡 Primary Decision Driver:** {', '.join(selected_pred.get('key_drivers', ['Baseline operational parameters']))}")

            return selected_zone_id

    except Exception as e:
        st.error(f"⚠️ Error generating priority rankings: {e}")
        return current_selected
