"""
UrbanShield - Explainable Recommendations Component
Renders plain-language explainable action plans generated by the RECOMMEND layer.
Displays 3 distinct reasoning dimensions: Environmental Drivers, Asset Protection, and Optimization Rationale.
"""

import streamlit as st
from config import SEVERITY_CONFIG
from services.agent_service import get_pipeline_predictions, get_recommendations_and_allocations
from services.data_service import get_zones_summary

def render_recommendations_view(selected_zone_id: str = None):
    """
    Renders multi-dimensional explainable decision brief for the municipal commander.
    Handles empty data and missing zones safely.
    """
    if not selected_zone_id:
        selected_zone_id = st.session_state.get("selected_zone_id", "Z-01")

    try:
        predictions = get_pipeline_predictions() or []
        recommendations = get_recommendations_and_allocations() or {}
        zones = {z["zone_id"]: z for z in (get_zones_summary() or [])}

        # Empty state check
        if not predictions or not zones:
            st.info("ℹ️ No active recommendation brief available. Please check telemetry feed connection.")
            return

        # Find target zone prediction and recommendation
        target_pred = next((p for p in predictions if p["zone_id"] == selected_zone_id), None)
        if not target_pred:
            target_pred = sorted(predictions, key=lambda x: x.get("priority_rank", 99))[0]
            selected_zone_id = target_pred["zone_id"]

        target_rec = recommendations.get(selected_zone_id, {})
        target_zone = zones.get(selected_zone_id, {})

        severity = target_pred.get("severity", "Low")
        badge = SEVERITY_CONFIG.get(severity, {}).get("badge", severity)
        hex_color = SEVERITY_CONFIG.get(severity, {}).get("color", "#10B981")

        pumps = target_rec.get('allocated_pumps', 0)
        crews = target_rec.get('allocated_crews', 0)
        assets = ", ".join(target_zone.get('critical_assets', ['Standard Urban Infrastructure']))

        st.markdown(f"##### 🎯 Action Brief & Explainable Decision: [{selected_zone_id}] {target_zone.get('name', selected_zone_id)}")

        # ---------------------------------------------------------------------
        # 1. PRIMARY DISPATCH PROTOCOL BANNER
        # ---------------------------------------------------------------------
        st.markdown(
            f"""
            <div style="background-color: #1E293B; border-left: 5px solid {hex_color}; border-radius: 8px; padding: 14px 16px; margin-bottom: 12px; box-shadow: 0 2px 4px rgba(0,0,0,0.2);">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                    <span style="font-weight: 700; font-size: 1.0rem; color: #F8FAFC;">
                        🚀 Protocol: {target_rec.get('urgency', 'Standard')}
                    </span>
                    <span style="font-weight: 700; font-size: 0.85rem; color: {hex_color};">
                        Priority Rank #{target_pred.get('priority_rank', '-')} | {badge} (Risk: {target_pred.get('risk_score', 0.0):.2f})
                    </span>
                </div>
                <div style="font-size: 0.95rem; color: #E2E8F0; line-height: 1.45; margin-bottom: 10px;">
                    {target_rec.get('action_summary', 'No immediate intervention required.')}
                </div>
                <div style="font-size: 0.82rem; color: #94A3B8; border-top: 1px solid #334155; padding-top: 6px;">
                    <b>Deployed Assets:</b> 🚜 {pumps} Heavy Pumps &nbsp;|&nbsp; 👷 {crews} Rapid Response Crews &nbsp;|&nbsp; 🛡️ <b>Protected:</b> {assets}
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

        # ---------------------------------------------------------------------
        # 2. THREE-DIMENSIONAL REASONING CHAIN
        # ---------------------------------------------------------------------
        st.markdown("###### 🔍 Explainable Decision Chain (Why This Action?)")
        
        # Section 1: Environmental & Threat Drivers
        st.markdown("**1. 🌦️ Environmental & Sensor Drivers**")
        drivers = target_pred.get("key_drivers", [])
        if drivers:
            for d in drivers:
                st.markdown(f"- ⚠️ <span style='font-size: 0.88rem;'>{d}</span>", unsafe_allow_html=True)
        else:
            st.caption("ℹ️ No specific anomalous weather drivers reported for this zone.")

        # Section 2: Critical Asset & Population Protection Rationale
        st.markdown("**2. 🛡️ Critical Asset & Population Protection Rationale**")
        asset_rationale = target_rec.get("asset_protection_rationale")
        if asset_rationale:
            st.markdown(f"- 🏥 <span style='font-size: 0.88rem;'>{asset_rationale}</span>", unsafe_allow_html=True)
        else:
            pop = target_zone.get("population", 0)
            st.markdown(f"- 👥 <span style='font-size: 0.88rem;'>Protects {pop:,} residents and baseline infrastructure: {assets}.</span>", unsafe_allow_html=True)

        # Section 3: OR-Tools Optimization & Resource Rationale
        st.markdown("**3. 🧩 OR-Tools Resource Optimization Rationale**")
        opt_rationale = target_rec.get("optimization_rationale")
        if opt_rationale:
            st.markdown(f"- 💡 <span style='font-size: 0.88rem;'>{opt_rationale}</span>", unsafe_allow_html=True)
        else:
            if pumps > 0:
                st.markdown(f"- 💡 <span style='font-size: 0.88rem;'>Linear solver allocated {pumps} pump units to maximize flood mitigation ROI in high-consequence basin.</span>", unsafe_allow_html=True)
            else:
                st.markdown("- 💡 <span style='font-size: 0.88rem;'>Gravity drainage operational; equipment reserved for higher-priority severe flood zones.</span>", unsafe_allow_html=True)

    except Exception as e:
        st.error(f"⚠️ Error loading explainable recommendations: {e}")
