[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0B0F17"
secondaryBackgroundColor = "#151D2A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
